apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-streamer-spot-trades
  namespace: marketdata
  labels:
    app: event-streamer-spot-trades
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-streamer-spot-trades
  template:
    metadata:
      name: event-streamer-spot-trades
      labels:
        app: event-streamer-spot-trades
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      containers:
        - name: event-streamer-spot-trades
          image: event_streamer
          imagePullPolicy: IfNotPresent
          env:
            - name: FEATURE
              value: "SPOT_TRADE"
            - name: GRPC_PORT
              value: "9000"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: event-streamer-spot-trades
  namespace: marketdata
spec:
  selector:
    app: event-streamer-spot-trades
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      