apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-adaptor
  namespace: marketdata
  labels:
    app: websocket-adaptor
  annotations:
    prometheus.io/port: 8000                                                                                                                                                             │
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-adaptor
  template:
    metadata:
      name: websocket-adaptor
      labels:
        app: websocket-adaptor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      containers:
        - name: websocket-adaptor
          image: websocket_adaptor
          imagePullPolicy: IfNotPresent
          env:
            - name: SPOT_TRADES_SERVICE_ADDR
              value: "event-streamer-spot-trades.marketdata.svc.cluster.local:9000"
            - name: SPOT_TICKERS_SERVICE_ADDR
              value: "event-streamer-spot-tickers.marketdata.svc.cluster.local:9000"
            - name: HTTP_PORT
              value: "8000"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-adaptor
  namespace: marketdata
spec:
  type: ClusterIP
  selector:
    app: websocket-adaptor
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
